[2022-07-18 13:56:06,759] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.load manual__2022-07-18T13:55:57.095421+00:00 [queued]>
[2022-07-18 13:56:06,775] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_dag.load manual__2022-07-18T13:55:57.095421+00:00 [queued]>
[2022-07-18 13:56:06,775] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:56:06,775] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-18 13:56:06,775] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-18 13:56:06,803] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load> on 2022-07-18 13:55:57.095421+00:00
[2022-07-18 13:56:06,809] {standard_task_runner.py:52} INFO - Started process 3077 to run task
[2022-07-18 13:56:06,814] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load', 'manual__2022-07-18T13:55:57.095421+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpbhn1j26o', '--error-file', '/tmp/tmpm92o1ets']
[2022-07-18 13:56:06,816] {standard_task_runner.py:80} INFO - Job 39: Subtask load
[2022-07-18 13:56:06,915] {task_command.py:371} INFO - Running <TaskInstance: etl_dag.load manual__2022-07-18T13:55:57.095421+00:00 [running]> on host 70b17816bd7e
[2022-07-18 13:56:07,042] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T13:55:57.095421+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-18T13:55:57.095421+00:00
[2022-07-18 13:56:07,070] {logging_mixin.py:115} INFO -          song_name        artist_name                 played_at   timestamp
0           Avareh  Siavash Ghomayshi  2022-07-18T05:48:12.234Z  2022-07-18
1           Arezou  Siavash Ghomayshi  2022-07-17T20:44:56.091Z  2022-07-17
2           Tabiat  Siavash Ghomayshi  2022-07-17T20:41:01.954Z  2022-07-17
3          Setareh  Siavash Ghomayshi  2022-07-17T20:37:43.707Z  2022-07-17
4      Tasavor Kon  Siavash Ghomayshi  2022-07-17T20:34:02.940Z  2022-07-17
5  Daryaye Maghreb  Siavash Ghomayshi  2022-07-17T20:29:53.538Z  2022-07-17
6         Parandeh  Siavash Ghomayshi  2022-07-17T20:25:50.882Z  2022-07-17
7         Yadegari  Siavash Ghomayshi  2022-07-17T20:22:27.220Z  2022-07-17
[2022-07-18 13:56:07,075] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 108, in load
    song_df.to_csv(file_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/csv_data.csv'
[2022-07-18 13:56:07,088] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=load, execution_date=20220718T135557, start_date=20220718T135606, end_date=20220718T135607
[2022-07-18 13:56:07,102] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task load ([Errno 21] Is a directory: '/opt/airflow/data/csv_data.csv'; 3077)
[2022-07-18 13:56:07,145] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-18 13:56:07,183] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
